version: "3.7"

services:
  backend:
    container_name: "micro-live-chat-backend"
    image: node:10.16-slim
    working_dir: /backend/src
    entrypoint: ./.docker/entrypoint.sh
    volumes:
      - .:/backend/src
    ports: 
      - "4444:4444"
    depends_on: 
      - database
    networks:
      - app-network
  
  database:
    container_name: "micro-live-chat-database"
    image: library/postgres:9.6-alpine
    ports: 
      - "5433:5434"
    volumes: 
      - ./.docker/database/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root@123
      - POSTGRES_DB=database
    restart: always
    tty: true
    networks: 
      - app-network

  redis:
    image: redis:alpine
    container_name: micro-live-chat-redis
    volumes:
      - ./.docker/redisdata:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
 