name: CI

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: docker run rabbitmq
      run: |
        cd rabbitmq
        docker-compose up -d
        cd ..

    - name: Test container rabbitmq
      run: |
        docker run --network container:container-rabbitmq-queue appropriate/curl -s --retry 10 --retry-connrefused http://localhost:15672
   
    - name: docker run micro live manager
      run: |
        cd micro-live-manager
        docker-compose up -d
        cd ..

    - name: Test container micro-live-manager-frontend
    run: |
      docker run --network container:micro-live-manager-frontend appropriate/curl -s --retry 10 --retry-connrefused http://localhost:8000
  
    - name: docker run micro live streaming
      run: |
        cd micro-live-streaming
        docker-compose up -d
        cd ..